# Fase 1 - Extracción de Artículos desde PDFs Jurídicos
Esta Fase se lee documentos PDF legales desde la carpeta `data/`, los limpia, extrae los artículos y normaliza su contenido.

In [10]:
!pip install PyMupdf -q
!pip install pandas -q

In [11]:
import os
import requests
import fitz  # PyMuPDF
import re
import unicodedata
import json
from pathlib import Path
from collections import Counter
import pandas as pd

In [61]:
# Lista de URLs crudas (RAW) de GitHub
archivos_pdf = [
    {
        "nombre": "LOPDGDD_2018",
        "url": "https://raw.githubusercontent.com/JuanC-1976/TFM-R46-GrafosLegales/main/BOE-A-2018-16673.pdf",
        "tipo_documento": "Ley Orgánica",
        "fecha_publicacion": "2018-12-06",
        "entidad_normativa": "BOE",
        "es_oficial": True
    },
    {
        "nombre": "RGPD",
        "url": "https://raw.githubusercontent.com/JuanC-1976/TFM-R46-GrafosLegales/main/CELEX_32016R0679_ES_TXT.pdf",
        "tipo_documento": "Reglamento Europeo",
        "fecha_publicacion": "2016-04-27",
        "entidad_normativa": "Parlamento Europeo",
        "es_oficial": True
    },
    {
        "nombre": "GUIA_AEPD",
        "url": "https://raw.githubusercontent.com/JuanC-1976/TFM-R46-GrafosLegales/main/memoria-aepd-2024.pdf",
        "tipo_documento": "Guía Técnica",
        "fecha_publicacion": "2022-01-15",
        "entidad_normativa": "AEPD",
        "es_oficial": False
    },
    {   
        "nombre": "Ley_Organica_15_1999",
        "url": "https://raw.githubusercontent.com/JuanC-1976/TFM-R46-GrafosLegales/main/BOE-A-1999-23750-consolidado.pdf",
        "tipo_documento": "Ley Orgánica (derogada)",
        "fecha_publicacion": "1999-12-14",
        "entidad_normativa": "BOE",
        "es_oficial": True
    },
    {   
        "nombre":"Ley_13500_Andalucia",
        "url": "https://raw.githubusercontent.com/JuanC-1976/TFM-R46-GrafosLegales/main/13500.pdf",
        "tipo_documento": "Ley Autonómica",
        "fecha_publicacion": "2022-03-10",
        "entidad_normativa": "Junta de Andalucía",
        "es_oficial": True
    }
]

In [57]:
# Descargar PDF si no existe
def descargar_pdf_si_no_existe(doc):
    ruta_pdf = Path(f"temp_pdfs/{doc['nombre']}.pdf")
    if ruta_pdf.exists():
        print(f"[✔] Ya existe: {ruta_pdf.name}")
        return ruta_pdf

    print(f"[↓] Descargando: {doc['nombre']}")
    r = requests.get(doc["url"])
    if "application/pdf" not in r.headers.get("Content-Type", ""):
        print(f"[ERROR] No es un PDF válido: {doc['url']}")
        return None

    ruta_pdf.parent.mkdir(exist_ok=True)
    with open(ruta_pdf, "wb") as f:
        f.write(r.content)
        
        # Verificar que el PDF descargado se pueda abrir
    try:
        with fitz.open(ruta_pdf) as test_pdf:
            _ = test_pdf[0]  # fuerza lectura de primera página
    except Exception as e:
        print(f"[AVISO] PDF corrupto tras descarga: {e}")
        ruta_pdf.unlink()  # eliminar archivo dañado
        print(f"[] Reintentando descarga limpia...")
        return descargar_pdf_si_no_existe(doc)  # intento recursivo limpio
        
    return ruta_pdf

In [58]:
# Extraer texto desde PDF
def extraer_texto_pdf(doc):
    ruta_pdf = descargar_pdf_si_no_existe(doc)
    if not ruta_pdf:
        return None

    try:
        with fitz.open(ruta_pdf) as pdf:
            texto = "\n".join([pagina.get_text() for pagina in pdf])
            return normalizar(texto)
    except Exception as e:
        print(f"[ERROR] Fallo al leer {doc['nombre']}: {e}")
        return None

In [70]:
# Normaliza el texto sin perder símbolos jurídicos ni estructura básica
def normalizar(texto):
    texto = unicodedata.normalize('NFC', texto)
    texto = re.sub(r'Página\s+\d+', '', texto, flags=re.IGNORECASE)
    texto = re.sub(r'[ \t]+', ' ', texto)
    texto = re.sub(r'[^\w\s.,;:()¿?!¡ºª§«»"\'\-–\n]', '', texto)
    return texto.strip()

In [85]:
# Intentar extraer por artículos

articulos_totales = []
conteo_por_documento = {}    
for doc in archivos_pdf:
    nombre = doc["nombre"]
    texto = extraer_texto_pdf(doc)  
    if not texto:
        continue

    texto_limpio = texto  
    articulos = []
    
    # Patrón amplio para artículos, disposiciones, títulos, capítulos
    patron = r"(Artículo\s+\d+[ººª]?[\.:\-]?\s.*?|Artículo\s+único.*?|Disposición\s+(?:adicional|final|transitoria)\s+\w+.*?|Cap[ií]tulo\s+\w+.*?|Título\s+\w+.*?|Secci[oó]n\s+\w+.*?)(?=\s{2,}|\n|Artículo\s+|Disposición\s+|Cap[ií]tulo\s+|Título\s+|Secci[oó]n\s+|$)"
    partes = re.split(patron, texto_limpio)
    
    
    if len(partes) > 2: # División por encabezados bien formateados
        for encabezado, contenido in zip(partes[1::2], partes[2::2]):
            if len(contenido.strip()) > 50 and not contenido.lower().startswith("cve:"):
               tipo = (
                    "Artículo" if "artículo" in encabezado.lower()
                    else "Disposición" if "disposición" in encabezado.lower()
                    else "Capítulo" if "capítulo" in encabezado.lower()
                    else "Sección" if "sección" in encabezado.lower()
                    else "Otro"
               )
                
               articulos.append({
                   "Documento": nombre,
                   "Artículo N": re.search(r'\d+', encabezado).group() if re.search(r'\d+', encabezado) else encabezado.strip(),
                   "Contenido": normalizar(contenido),
                   "tipo_documento": doc.get("tipo_documento", ""),
                   "fecha_publicacion": doc.get("fecha_publicacion", ""),
                   "entidad_normativa": doc.get("entidad_normativa", ""),
                   "es_oficial": doc.get("es_oficial", False)
               })
    else:
        # Extracción por bloques alternativos
        bloques = re.findall(
            r'(Título\s+[IVXLC\d]+|Capítulo\s+[IVXLC\d]+|Sección\s+[A-Za-z]+|Disposición\s+\w+)\.?\s+(.*?)(?=Título\s+[IVXLC\d]+|Capítulo\s+[IVXLC\d]+|Sección\s+[A-Za-z]+|Disposición\s+\w+|$)',
            texto_limpio, re.DOTALL)
        for encabezado, contenido in bloques:
            if len(contenido.strip()) > 50:
                articulos.append({
                    "Documento": nombre,
                    "Artículo N": encabezado.strip(),
                    "Contenido": normalizar(contenido),
                    "tipo_documento": doc.get("tipo_documento", ""),
                    "fecha_publicacion": doc.get("fecha_publicacion", ""),
                    "entidad_normativa": doc.get("entidad_normativa", ""),
                    "es_oficial": doc.get("es_oficial", False)
                })
                
    # Vista previa en tabla
    if articulos:
        conteo_por_documento[nombre] = len(articulos)
        articulos_totales.extend(articulos)
        
        # Mostrar preview
        df_vista = pd.DataFrame(articulos)
        df_vista["Vista previa"] = df_vista["Contenido"].str.slice(0, 200) + "..."
        display(df_vista[["Documento", "Artículo N", "Vista previa"]].head(10))
        print(f" {nombre}: {len(articulos)} bloques extraídos")
      
    else:
        print(f" No se encontraron artículos o bloques válidos en {nombre}.")
        print(f"No se encontraron artículos o bloques válidos en {nombre}.")

[✔] Ya existe: LOPDGDD_2018.pdf

,Documento,Artículo N,Vista previa
0,LOPDGDD_2018,20,cve: BOE-A-2018-16673\nVerificable en http:www...
1,LOPDGDD_2018,Capítulo I.,Disposiciones generales. Medidas de responsabi...
2,LOPDGDD_2018,50,cve: BOE-A-2018-16673\nVerificable en http:www...
3,LOPDGDD_2018,2,Potestades de investigación y planes de audito...
4,LOPDGDD_2018,3,Otras potestades de la Agencia Española de Pro...
5,LOPDGDD_2018,2,Coordinación en el marco de los procedimientos...
6,LOPDGDD_2018,Título VIII.,Procedimientos en caso de posible vulneración ...
7,LOPDGDD_2018,80,cve: BOE-A-2018-16673\nVerificable en http:www...
8,LOPDGDD_2018,Disposición adicional primera.,Medidas de seguridad en el ámbito del sector p...
9,LOPDGDD_2018,Disposición adicional segunda.,Protección de datos y transparencia y acceso a...

 LOPDGDD_2018: 231 bloques extraídos
[✔] Ya existe: RGPD.pdf

  Documento Artículo N                                       Vista previa
0      RGPD          1  Objeto \n1.\nEl presente Reglamento establece ...
1      RGPD          2  Ámbito de aplicación material \n1.\nEl present...
2      RGPD          3  Ámbito territorial \n1.\nEl presente Reglament...
3      RGPD          4  Definiciones \nA efectos del presente Reglamen...
4      RGPD          5  Principios relativos al tratamiento \n1.\nLos ...
5      RGPD          6  Licitud del tratamiento \n1.\nEl tratamiento s...
6      RGPD          7  Condiciones para el consentimiento \n1.\nCuand...
7      RGPD          8  Condiciones aplicables al consentimiento del n...
8      RGPD          9  Tratamiento de categorías especiales de datos ...
9      RGPD         10  Tratamiento de datos personales relativos a co...

 RGPD: 101 bloques extraídos
[✔] Ya existe: GUIA_AEPD.pdf

,Documento,Artículo N,Vista previa
0,GUIA_AEPD,Sección Primera de la Sala de lo Contencioso,Administrativo de la Audiencia Nacional que \n...
1,GUIA_AEPD,"Disposición transitoria segunda LOPDPGDD,",se continua con el proceso de adaptación de lo...
2,GUIA_AEPD,18,aunque haya acreditado la contestación a la \n...
3,GUIA_AEPD,Capítulo V del RGPD al haber,declarado inválido el TJUE la anterior decisió...
4,GUIA_AEPD,32,falta de medidas de seguridad básicas. Multa \...
5,GUIA_AEPD,25,diseño desde el principio en el que los datos ...
6,GUIA_AEPD,35,realización de una evaluación de impacto. \nMu...
7,GUIA_AEPD,32,"Artículo \n83.4 del RGPD, una multa de 200.000..."
8,GUIA_AEPD,7,de inscripción no ofrecía la posibilidad de \n...
9,GUIA_AEPD,37,A lo largo del procedimiento se han corregido ...

 GUIA_AEPD: 17 bloques extraídos
[✔] Ya existe: Ley_Organica_15_1999.pdf

,Documento,Artículo N,Vista previa
0,Ley_Organica_15_1999,3,5\nTÍTULO II. Principios de la protección de d...
1,Ley_Organica_15_1999,12,9\nTÍTULO III. Derechos de las personas . . . ...
2,Ley_Organica_15_1999,19,10\nTÍTULO IV. Disposiciones sectoriales . . ....
3,Ley_Organica_15_1999,24,12\nCAPÍTULO II. Ficheros de titularidad priva...
4,Ley_Organica_15_1999,32,15\nTÍTULO V. Movimiento internacional de dato...
5,Ley_Organica_15_1999,34,15\nTÍTULO VI. Agencia de Protección de Datos ...
6,Ley_Organica_15_1999,40,18\nBOLETÍN OFICIAL DEL ESTADO\nLEGISLACIÓN CO...
7,Ley_Organica_15_1999,42,19\nTÍTULO VII. Infracciones y sanciones. . . ...
8,Ley_Organica_15_1999,49,19\nDisposiciones adicionales . . . . . . . . ...
9,Ley_Organica_15_1999,Disposición adicional tercera. Tratamiento de ...,Maleantes y de Peligrosidad y Rehabilitación S...

 Ley_Organica_15_1999: 69 bloques extraídos
[✔] Ya existe: Ley_13500_Andalucia.pdf

,Documento,Artículo N,Vista previa
0,Ley_13500_Andalucia,Sección Octava. Procedimien-,to 8662025 . . . . . . . . . . . . . . . . . ....
1,Ley_13500_Andalucia,2,Este Convenio afecta a todos los trabajadoresa...
2,Ley_13500_Andalucia,3,El presente Convenio será de aplicación en tod...
3,Ley_13500_Andalucia,4,1. Vigencia. El presente Convenio Colectivo en...
4,Ley_13500_Andalucia,5,Se acuerda un incremento salarial para el año ...
5,Ley_13500_Andalucia,6,Las condiciones de cualquier clase pactadas en...
6,Ley_13500_Andalucia,7,Toda cláusula contractual que sea contraria a ...
7,Ley_13500_Andalucia,8,A. A fecha de la firma del presente convenio a...
8,Ley_13500_Andalucia,9,"Cuando concurran causas económicas, técnicas, ..."
9,Ley_13500_Andalucia,10,1. Se constituye una Comisión Paritaria para l...

 Ley_13500_Andalucia: 48 bloques extraídos

In [89]:
# Crear carpeta temporal para guardar PDFs
# Crear carpetas si no existen
output_dir = Path("jsons_articulos")
output_dir.mkdir(parents=True, exist_ok=True)

pdf_dir = Path("temp_pdfs")
pdf_dir.mkdir(parents=True, exist_ok=True)

In [90]:
# Ruta de salida
json_salida = output_dir / "bloques_legales_unificado.json"

# Guardar los artículos unificados
with open(json_salida, "w", encoding="utf-8") as f:
    json.dump(articulos_totales, f, ensure_ascii=False, indent=2)
    print(f" JSON unificado guardado en: {json_salida}")

✅ JSON unificado guardado en: jsons_articulos\bloques_legales_unificado.json

# Fase 2 -Extracción de información semántica
Este notebook lee documentos PDF legales desde la carpeta data/, los limpia, extrae los artículos y normaliza su contenido

In [96]:
!pip install --upgrade openai -q
!pip install --upgrade requests -q

In [125]:
from openai import OpenAI
import requests
# Configurar la API Key de OpenAI
openai.api_key ="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"
client = OpenAI(api_key=openai.api_key)

# Crear carpeta de salida dentro de /Notebooks/
output_dir = Path("Notebooks/jsons_semanticos")
output_dir.mkdir(parents=True, exist_ok=True)

In [131]:
# Leer el archivo JSON desde GitHub (Fase 1)
url_json = "https://raw.githubusercontent.com/JuanC-1976/TFM-R46-GrafosLegales/main/Notebooks/bloques_legales_unificado.json"
respuesta = requests.get(url_json)

# Convertir a lista de artículos
articulos = respuesta.json()
print(f" Se cargaron {len(articulos)} bloques legales desde GitHub.")

 Se cargaron 466 bloques legales desde GitHub.

In [ ]:
# Función que envía cada bloque a GPT-4o y devuelve respuesta estructurada
def analizar_bloque_con_gpt(bloque_texto):
    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": (
                    "Extrae entidades legales y relaciones del texto siguiente en formato JSON. "
                    "El JSON debe tener: documento, tipo, fecha, vigente, relaciones (lista de dicts)."
                )},
                {"role": "user", "content": bloque_texto}
            ],
            temperature=0.2
        )

        # Acceder correctamente al contenido según nueva API
        contenido = response.choices[0].message.content.strip()
        if not contenido:
            print("⚠️ Respuesta vacía del modelo.")
            return None
        try:
            return json.loads(contenido)
        except json.JSONDecodeError as e:
            print("❌ Error decodificando JSON:", e)
            print("🔍 Respuesta cruda del modelo:", contenido)
            return None


   # except Exception as e:
    #    print("❌ Error procesando bloque:", e)
     #   return None

In [ ]:
import json
from tqdm import tqdm

resultados_semanticos = []

# Procesar todos los bloques
for i, bloque in enumerate(tqdm(articulos, desc="Procesando bloques")):
    print(f"🔎 Procesando bloque {i+1}/{len(articulos)}")
    resultado = analizar_bloque_con_gpt(bloque["Contenido"])
    if resultado:
        resultado["documento_origen"] = bloque["Documento"]
        resultados_semanticos.append(resultado)

# Convertir a DataFrame
df_semanticos = pd.DataFrame(resultados_semanticos)

# Guardar como JSON estructurado
json_salida = output_dir / "bloques_semanticos.json"
with open(json_salida, "w", encoding="utf-8") as f:
    json.dump(resultados_semanticos, f, ensure_ascii=False, indent=2)

print(f"\n✅ Se procesaron correctamente {len(df_semanticos)} de {len(articulos)} bloques.")
print(f"📁 Archivo guardado: {json_salida}")

# Mostrar primeras filas
pd.set_option("display.max_colwidth", 180)
display(df_semanticos[["documento_origen", "tipo", "fecha", "vigente", "relaciones"]].head(5))

In [133]:
# Convertir los resultados enriquecidos a DataFrame
df_semanticos = pd.DataFrame(resultados_semanticos)

# Mostrar resumen
print(f" Se procesaron correctamente {len(df_semanticos)} de {len(articulos)} bloques.")

# Mostrar vista previa
pd.set_option("display.max_colwidth", 180)
display(df_semanticos[["documento_origen", "tipo", "fecha", "vigente", "relaciones"]].head(5))

 Se procesaron correctamente 0 de 466 bloques.

KeyError: "None of [Index(['documento_origen', 'tipo', 'fecha', 'vigente', 'relaciones'], dtype='object')] are in the [columns]"

In [127]:
import json

# ✅ Elegir el primer bloque para test
bloque_prueba = articulos[0]["Contenido"]

# ✅ Enviar a GPT-4o (sin json.loads aún)
response_test = client.chat.completions.create(
    model="gpt-4o",
    messages=[
        {
            "role": "system",
            "content": (
                "Extrae entidades legales y relaciones del texto siguiente en formato JSON. "
                "El JSON debe tener los campos: documento, tipo, fecha, vigente, relaciones (lista de dicts)."
            )
        },
        {
            "role": "user",
            "content": bloque_prueba
        }
    ],
    temperature=0.2
)

# ✅ Mostrar texto crudo recibido
texto_bruto = response_test.choices[0].message.content
print("📄 Respuesta cruda del modelo:\n", texto_bruto)

# ✅ Limpiar si viene con triple backticks
if "```json" in texto_bruto:
    texto_bruto = texto_bruto.split("```json")[-1]
if "```" in texto_bruto:
    texto_bruto = texto_bruto.split("```")[0]

# ✅ Intentar parsear el JSON
try:
    resultado_json = json.loads(texto_bruto)
    print("\n✅ JSON estructurado correctamente:")
    display(resultado_json)
except Exception as e:
    print("\n❌ Error al convertir a JSON:", e)

📄 Respuesta cruda del modelo:
 ```json
{
  "documento": "BOE-A-2018-16673",
  "tipo": "BOLETÍN OFICIAL DEL ESTADO",
  "fecha": "2018-12-06",
  "vigente": true,
  "relaciones": []
}
```

✅ JSON estructurado correctamente:

{'documento': 'BOE-A-2018-16673',
 'tipo': 'BOLETÍN OFICIAL DEL ESTADO',
 'fecha': '2018-12-06',
 'vigente': True,
 'relaciones': []}

In [130]:
resultados_semanticos = []

# Probar con pocos al inicio: articulos[:3]
for i, bloque in enumerate(articulos):
    print(f"🧠 Procesando bloque {i+1}/{len(articulos)}")
    resultado = analizar_bloque_con_gpt(bloque["Contenido"])
    if resultado:
        resultado["documento_origen"] = bloque["Documento"]
        resultados_semanticos.append(resultado)

print(f"\n Total de bloques enriquecidos: {len(resultados_semanticos)}")

🧠 Procesando bloque 1/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 2/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 3/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 4/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 5/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 6/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 7/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 8/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 9/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 10/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 11/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 12/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 13/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 14/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 15/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 16/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 17/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 18/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 19/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 20/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 21/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 22/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 23/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 24/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 25/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 26/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 27/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 28/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 29/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 30/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 31/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 32/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 33/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 34/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 35/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 36/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 37/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 38/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 39/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 40/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 41/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 42/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 43/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 44/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 45/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 46/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 47/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 48/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 49/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 50/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 51/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 52/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 53/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 54/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 55/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 56/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 57/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 58/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 59/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 60/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 61/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 62/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 63/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 64/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 65/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 66/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 67/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 68/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 69/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 70/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 71/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 72/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 73/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 74/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 75/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 76/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 77/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 78/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 79/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 80/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 81/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 82/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 83/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 84/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 85/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 86/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 87/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 88/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 89/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 90/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 91/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 92/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 93/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 94/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 95/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 96/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 97/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 98/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 99/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 100/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 101/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 102/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 103/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 104/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 105/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 106/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 107/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 108/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 109/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 110/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 111/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 112/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 113/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 114/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 115/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 116/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 117/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 118/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 119/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 120/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 121/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 122/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 123/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 124/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 125/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 126/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 127/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 128/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 129/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 130/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 131/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 132/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 133/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 134/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 135/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 136/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 137/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 138/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 139/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 140/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 141/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 142/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 143/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 144/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 145/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 146/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 147/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 148/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 149/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 150/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 151/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 152/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 153/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 154/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 155/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 156/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 157/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 158/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 159/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 160/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 161/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 162/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 163/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 164/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 165/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 166/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 167/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 168/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 169/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 170/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 171/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 172/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 173/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 174/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 175/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 176/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 177/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 178/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 179/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 180/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 181/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 182/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 183/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 184/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 185/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 186/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 187/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 188/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 189/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 190/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 191/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 192/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 193/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 194/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 195/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 196/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 197/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 198/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 199/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 200/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 201/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 202/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 203/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 204/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 205/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 206/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 207/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 208/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 209/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 210/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 211/466
❌ Error procesando bloque: 'OpenAI' object has no attribute 'Chat'
🧠 Procesando bloque 212/466

In [ ]:
# Guardar como JSON enriquecido
ruta_salida = output_dir / "bloques_semanticos.json"
with open(ruta_salida, "w", encoding="utf-8") as f:
    json.dump(resultados_semanticos, f, ensure_ascii=False, indent=2)

print(f"Archivo guardado en: {ruta_salida.resolve()}")